apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-hello-world
  title: Create a simple Hello World project
  description: Generates a minimal project with just a README file.
  tags:
    - demo
    - beginner
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Basic Information
      required:
        - name
      properties:
        name:
          title: Project name
          type: string
          description: The name of your new project.

  steps:
    - id: readme
      name: Create README
      action: fs:write
      input:
        path: ./README.md
        content: |
          # ${{ parameters.name }}

          A simple Hello World project created with Backstage.

          ## Getting Started

          This is a minimal project template.

          ## Next Steps

          - Add your code
          - Configure your CI/CD
          - Deploy your service

    - id: catalog
      name: Create catalog-info.yaml
      action: fs:write
      input:
        path: ./catalog-info.yaml
        content: |
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: ${{ parameters.name }}
            description: A simple Hello World project
            tags:
              - demo
              - beginner
          spec:
            type: service
            lifecycle: experimental
            owner: team-a

    - id: publish
      name: Create GitHub repository
      action: publish:github
      input:
        repoUrl: github.com?owner=my-org&repo=${{ parameters.name }}
        repoVisibility: public

    - id: register
      name: Register in Backstage catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Open Repository
        url: ${{ steps.publish.output.remoteUrl }}

