apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-service-simple
  title: Simple Service
  description: A simple service template that creates a component in the Backstage catalog
  tags:
    - service
    - demo
    - learning
    - simple
spec:
  owner: team-a
  type: service

  parameters:
    - title: Fill in some basic information
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:help: This will be used as the component name in Backstage
        description:
          title: Description
          type: string
          description: Description of the component
          default: A service created from Backstage template
        owner:
          title: Owner
          type: string
          description: Owner of the component (team or user)
          default: team-a
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - Group
              - User
        system:
          title: System
          type: string
          description: System this component belongs to (optional)
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - System
        lifecycle:
          title: Lifecycle
          type: string
          description: Lifecycle stage
          enum:
            - experimental
            - development
            - production
            - deprecated
          default: development
          enumNames:
            - Experimental
            - Development
            - Production
            - Deprecated
        tags:
          title: Tags
          type: array
          description: Tags for the component (comma-separated)
          items:
            type: string
          default:
            - service
            - demo

  steps:
    - id: register
      name: Register Component
      action: catalog:write
      input:
        entities:
          - apiVersion: backstage.io/v1alpha1
            kind: Component
            metadata:
              name: ${{ parameters.name }}
              namespace: default
              description: ${{ parameters.description }}
              tags:
                - service
                - demo
            spec:
              type: service
              lifecycle: ${{ parameters.lifecycle }}
              owner: ${{ parameters.owner }}

  output:
    links:
      - title: View in catalog
        icon: catalog
        entityRef: component:default/${{ parameters.name }}

