apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: simple-service-simple
  title: Simple Service
  description: A simple service template that creates a component in the Backstage catalog
  tags:
    - service
    - demo
    - learning
    - simple
spec:
  type: service
  owner: team-a
  templater: cookiecutter
  path: .
